config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :projects
  root 'statics#index'
  get '/resume' => 'statics#resume'
  resources :random_thoughts
  resources :books

  get '/webhook/whatsapp' => 'webhooks#whatsapp'
  post '/webhook/whatsapp' => 'webhooks#whatsapp'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quote.rb
class Quote
  include Mongoid::Document
  include Mongoid::Timestamps
  field :quote, type: String
  field :said_by, type: String
  field :author_mugshot, type: String
  field :rating, type:Integer
  field :tags, type: Array, default: []
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.order_by(:rating => 'desc')
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params[:quote][:tags] = params[:quote][:tags].split(',')
      params.require(:quote).permit(:quote, :said_by, :author_mugshot, :rating, :tags => [])
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(quote) do |f| %>
    <% if quote.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

          <ul>
            <% quote.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :quote %>
      <%= f.text_field :quote %>
    </div>

    <div class="field">
      <%= f.label :said_by %>
      <%= f.text_field :said_by %>
    </div>

    <div class="field">å
      <%= f.label :author_mugshot %>
      <%= f.text_field :author_mugshot %>
    </div>

    <div class="field">
      <%= f.label :rating %>
      <%= f.text_field :rating %>
    </div>

    <div class="field">
      <%= f.label :tags %>
      <%= f.text_field :tags %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>
<style>
  .quote {
    margin-top: 2%;
    margin-bottom: 2%;
    height: auto;
    padding: 4%;
  }

  .quote-text {
    font-size: x-large;
    color: #3a4459;
    text-align: center;
    text-space: 1px;
    line-height: 100%;
  }

  .said-by {
    float: right;
    display: table-cell;
    vertical-align: middle;
    text-align: center;
    font-size: large;
  }

  .tags {
    float: right;
    font-size: x-small;
    color: #3a4459;
  }

  h4 {
    font-weight: lighter;
  }

</style>

<div class="breadcrumb">
  <h4><a href="/"> Home </a> > Favourite Quotes </h4>
</div>
<hr>
<% @quotes.each do |quote| %>
    <div class="quote">
      <div class="quote-text"><%= quote.quote %> </div><br>
      <div>
        <div class="said-by"> -  <span style="color: #f22f2f;"><%= quote.said_by %> </span></div><br>
        <div class="tags">Tags: <%= quote.tags.join(', ') %> </div><br>
        <% if admin? %>
          <%= link_to 'Show', quote %> |
          <%= link_to 'Edit', edit_quote_path(quote) %> |
          <%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
<% end %>


<%= link_to 'New Quote', new_quote_path if admin? %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @quote.quote %>
</p>

<p>
  <strong>Said by:</strong>
  <%= @quote.said_by %>
</p>

<p>
  <strong>Author mugshot:</strong>
  <%= @quote.author_mugshot %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @quote.tags %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>