config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :projects
  root 'statics#index'
  get '/resume' => 'statics#resume'
  resources :random_thoughts
  resources :books

  get '/webhook/whatsapp' => 'webhooks#whatsapp'
  post '/webhook/whatsapp' => 'webhooks#whatsapp'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/random_thought.rb
class RandomThought
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :short_description, type: String
  field :long_description, type: String
  field :rating, type:Integer
  field :visible, type:Integer
  field :tags, type: Array
end

app/controllers/random_thoughts_controller.rb
class RandomThoughtsController < ApplicationController
  before_action :set_random_thought, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, :except => [:index, :show]

  # GET /random_thoughts
  # GET /random_thoughts.json
  def index
    if params[:view] == 'admin'
      @random_thoughts = RandomThought.order_by(:rating => 'desc')
    else
      @random_thoughts = RandomThought.where(:visible => 1)
    end
  end

  # GET /random_thoughts/1
  # GET /random_thoughts/1.json
  def show
  end

  # GET /random_thoughts/new
  def new
    @random_thought = RandomThought.new
  end

  # GET /random_thoughts/1/edit
  def edit
  end

  # POST /random_thoughts
  # POST /random_thoughts.json
  def create
    @random_thought = RandomThought.new(random_thought_params)

    respond_to do |format|
      if @random_thought.save
        format.html { redirect_to @random_thought, notice: 'Random thought was successfully created.' }
        format.json { render :show, status: :created, location: @random_thought }
      else
        format.html { render :new }
        format.json { render json: @random_thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /random_thoughts/1
  # PATCH/PUT /random_thoughts/1.json
  def update
    respond_to do |format|
      if @random_thought.update(random_thought_params)
        format.html { redirect_to @random_thought, notice: 'Random thought was successfully updated.' }
        format.json { render :show, status: :ok, location: @random_thought }
      else
        format.html { render :edit }
        format.json { render json: @random_thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /random_thoughts/1
  # DELETE /random_thoughts/1.json
  def destroy
    @random_thought.destroy
    respond_to do |format|
      format.html { redirect_to random_thoughts_url, notice: 'Random thought was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_random_thought
      @random_thought = RandomThought.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def random_thought_params
      params[:random_thought][:tags] = params[:random_thought][:tags].split(',')
      params.require(:random_thought).permit(:title, :short_description, :long_description, :rating, :visible, :tags => [])
    end
end

app/helpers/random_thoughts_helper.rb
module RandomThoughtsHelper

end

app/views/random_thoughts/_form.html.erb
<%= form_for(random_thought) do |f| %>
    <% if random_thought.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(random_thought.errors.count, "error") %> prohibited this random_thought from being saved:</h2>

          <ul>
            <% random_thought.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :short_description %>
      <%= text_area :random_thought, :short_description %>
    </div>

    <div class="field">
      <%= f.label :long_description %>
      <%= text_area :random_thought, :long_description %>
    </div>


    <div class="field">
      <%= f.label :rating %>
      <%= f.text_field :rating %>
    </div>

    <div class="field">
      <%= f.label :visible %>
      <%= f.text_field :visible %>
    </div>

    <div class="field">
      <%= f.label :tags %>
      <%= f.text_field :tags %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/random_thoughts/edit.html.erb
<h1>Editing Random Thought</h1>

<%= render 'form', random_thought: @random_thought %>

<%= link_to 'Show', @random_thought %> |
<%= link_to 'Back', random_thoughts_path %>

app/views/random_thoughts/index.html.erb
<p id="notice"><%= notice %></p>

<style>

  .thought  {
    padding: 4%;
  }
  .thought-title {
    color: #3a4459;
    font-size: x-large;
    text-align: justify;
    line-height: 120%;
  }

  .thought-short-text {
    font-size: larger;
    text-align: justify;
    line-height: 120%;
  }

  .thought-long-text {
    font-size: large;
    text-align: justify;
    line-height: 120%;
    margin: 0 !important;
  }

  .tags {
    float: left;
    font-size: small;
  }

  h4 {
    font-weight: lighter;
  }
</style>

<div class="breadcrumb">
  <h4><a href="/"> Home </a> > Random Thoughts </h4>
</div>
<hr>
<% @random_thoughts.each do |random_thought| %>
    <div class="thought">
    <div class="thought-title"><%= random_thought.title %> </div><br>
    <b>tldr;</b> <div class="thought-short-text"><%==  random_thought.short_description %></div><br>
      <%= simple_format(add_href_to_link(random_thought.long_description)[0..450], :class => 'thought-long-text')%>
      <% if random_thought.long_description.length > 450 %>
        <%= link_to 'Continue reading ...', random_thought %><br><br>
      <% end %>
      <div>
        <div class="tags">Tags: <span style="color: #f22f2f;"><%= random_thought.tags.join(', ') %></span> </div><br>
        <% if admin? %>
            <%= link_to 'Show', random_thought %> |
            <%= link_to 'Edit', edit_random_thought_path(random_thought) %> |
            <%= link_to 'Destroy', random_thought, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
    </div>
<% end %>

<br>
<%= link_to 'New Random Thought', new_random_thought_path if admin? %>

app/views/random_thoughts/new.html.erb
<h1>New Random Thought</h1>

<%= render 'form', random_thought: @random_thought %>

<%= link_to 'Back', random_thoughts_path %>

app/views/random_thoughts/show.html.erb
<p id="notice"><%= notice %></p>

<style>

  .thought  {
    padding: 4%;
  }
  .thought-title {
    color: #3a4459;
    font-size: x-large;
    text-align: justify;
    line-height: 120%;
  }

  .thought-short-text {
    font-size: larger;
    text-align: justify;
    line-height: 120%;
  }

  .thought-long-text {
    font-size: large;
    text-align: justify;
    line-height: 120%;
    margin: 0 !important;
  }

  .tags {
    float: left;
    font-size: small;
  }

  h4 {
    font-weight: lighter;
  }
</style>

<div class="breadcrumb">
  <h4><a href="/"> Home </a> > Random Thoughts </h4>
</div>
<hr>
<div class="thought">
  <div class="thought-title"><%= @random_thought.title %> </div><br>
  <b>tldr;</b> <div class="thought-short-text"><%==  @random_thought.short_description %></div><br>
  <div class="tags">Tags: <span style="color: #f22f2f;"><%= @random_thought.tags.join(', ') %></span> </div><br>
  <%= simple_format(add_href_to_link(@random_thought.long_description), :class => 'thought-long-text')%>
      <div>
        <% if admin? %>
            <%= link_to 'Show', @random_thought %> |
            <%= link_to 'Edit', edit_random_thought_path(@andom_thought) %> |
            <%= link_to 'Destroy', @random_thought, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
    </div>
<br>
<%= link_to 'New Random Thought', new_random_thought_path if admin? %>