config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :projects
  root 'statics#index'
  get '/resume' => 'statics#resume'
  resources :random_thoughts
  resources :books

  get '/webhook/whatsapp' => 'webhooks#whatsapp'
  post '/webhook/whatsapp' => 'webhooks#whatsapp'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :short_description, type: String
  field :long_description, type: String
  field :why, type: String
  field :how, type: String
  field :what_is_next, type: String
  field :service_url, type: String
  field :cover_image, type: String
  field :video_demo, type: String
  field :rating, type:Integer
  field :technologies_used, type: Array, default: []
  field :screenshot_links, type: Array, default: []
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, :except => [:index, :show]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.order_by(:rating => 'desc')
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params[:project][:technologies_used] = params[:project][:technologies_used].split(',')
      params[:project][:screenshot_links] = params[:project][:screenshot_links].split(',')
      params.require(:project).permit(:title, :short_description, :long_description, :why, :how, :what_is_next, :service_url, :cover_image, :video_demo, :rating, :technologies_used => [], :screenshot_links => [])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
    <% if project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :short_description %>
      <%= text_area(:project, :short_description) %>
    </div>

    <div class="field">
      <%= f.label :long_description %>
      <%= text_area(:project, :long_description) %>
    </div>

    <div class="field">
      <%= f.label :why %>
      <%= text_area(:project,  :why) %>
    </div>

    <div class="field">
      <%= f.label :how %>
      <%= f.text_field :how %>
    </div>

    <div class="field">
      <%= f.label :what_is_next %>
      <%= text_area(:project, :what_is_next) %>
    </div>

    <div class="field">
      <%= f.label :service_url %>
      <%= f.text_field :service_url %>
    </div>

    <div class="field">
      <%= f.label :cover_image %>
      <%= f.text_field :cover_image %>
    </div>

    <div class="field">
      <%= f.label :video_demo %>
      <%= f.text_field :video_demo %>
    </div>
    <div class="field">
      <%= f.label :rating %>
      <%= f.text_field :rating %>
    </div>
    <div class="field">
      <%= f.label :technologies_used %>
      <%= f.text_field :technologies_used %>
    </div>

    <div class="field">
      <%= f.label :screenshot_links %>
      <%= f.text_field :screenshot_links %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<style>
  .technologies-used {
    #float: left;
    font-size: small;
    color: #3a4459;
  }

  .project {
    padding-top: 5%;
    padding-bottom: 5%;
    #padding-left: 1%;
    #padding-right: 1%;
    display:inline-block;
    width: 100%;
  }

  .project-name {
    padding-top: 10px;
    font-size: x-large;
    color: #3a4459;
  }

  .short-description {
    font-size: medium;
    text-align: justify;
    margin: 0 !important;
  }

  h4 {
    font-weight: lighter;
  }

  .details {
    #margin-left: 45%;
    #padding-top: 2%;
    #padding-left: 4%;
    #position: relative;
    #float:right;
    padding-right: 1%;
    text-align: justify;
    #flex-wrap: wrap;
    #width: auto;
    #display: inline-block;

  }


  #showcase {
    /* Prevent vertical gaps */
    display: inline-block;
    width: 55%;
    height: 40%;
    margin-left: 2%;
    box-shadow: 5px 10px 10px #888888;
    float: right;
  }

  #showcase img {
    /* Just in case there are inline attributes */
    width: 100% !important;
    height: 100% !important;
    align-content: center;
  }

</style>

<div class="breadcrumb">
  <h4><a href="/"> Home </a> > Side projects </h4>
</div>
<hr>
<div class="container">
  <% @projects.each do |project| %>
      <div class="project">
        <span class="project-name"><%= project.title %></span>
        <% if project.service_url.present? %> | Visit: <a href="<%= project.service_url %>"><%= project.service_url %></a><% end %>
        <br><br>
        <div id="showcase">
          <img src="<%= project.cover_image %>">
          <% project.screenshot_links.each do |screenshot| %>
            <!-- <img src="<%= screenshot %>"> -->
          <% end %>
        </div>

        <span class="details">
          <br>
          <%== simple_format(project.short_description, :class => 'short-description') %><br>
          <div class="project-name"> Why?</div><br>
          <%== simple_format(project.why, :class => 'short-description')  %>
          <span class="technologies-used"><br>
            Made with: <%= project.technologies_used.join(', ') %>
          </span>
          <br><br>
          <% if project.screenshot_links.first != project.cover_image %>
            <%= link_to 'See more screenshots', project %>
          <% end %>
          <% if admin? %>
              <br>
              <%= link_to 'Show', project %>
              <%= link_to 'Edit', edit_project_path(project) %>
              <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </span>
      </div>
  <% end %>
</div>

<%= link_to 'New Project', new_project_path if admin? %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<style>
  h4 {
    font-weight: lighter;
  }

  .showcase {
    /* Prevent vertical gaps */
    display: inline-block;
    width: 80%;
    height: 40%;
    margin: 2%;
    box-shadow: 2px 6px 10px 3px #888888
  }

    .showcase img {
      height: 100%;
      width: 100%;
      margin-left:auto;
      margin-right:auto;
      display: block;
    }

   .container {
     text-align: center;
   }
</style>
<p id="notice"><%= notice %></p>

<div class="breadcrumb">
  <h4><a href="/"> Home </a> > <a href="/projects">Side projects</a> > <%= @project.title %></h4>
  <hr>
</div>

<div class="container">
  <div class="showcase">
    <img src="<%= @project.cover_image %>">
  </div><br>
  <% @project.screenshot_links.each do |screenshot| %>
      <div class="showcase">
        <img src="<%= screenshot%>">
      </div>
  <% end %>
</div>
<% if admin? %>
  <%= link_to 'Edit', edit_project_path(@project) %> |
  <%= link_to 'Back', projects_path %>
<% end %>