config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :projects
  root 'statics#index'
  get '/resume' => 'statics#resume'
  resources :random_thoughts
  resources :books

  get '/webhook/whatsapp' => 'webhooks#whatsapp'
  post '/webhook/whatsapp' => 'webhooks#whatsapp'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Avinash Varma | <%= title_name %></title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
              (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-36491681-1', 'auto');
      ga('send', 'pageview');

  </script>
  <br><br>
  <div class="name"><a style="text-decoration: none !important;color:inherit;" href="/">Avinash Varma</a></div>

  <div class="navigation-links">
    <%= link_to('Side Projects', projects_path) %>  |
    <%= link_to('Reading list', books_path) %> |
    <%= link_to('Random Thoughts', random_thoughts_path) %> |
    <%= link_to('Favourite Quotes', quotes_path) %> |
    <%= link_to('Resume', resume_path) %>
  </div>

    <%= yield %>
  </body>
<div class="footer">
  <hr>
  &copy; Avinash Varma
</div>
</html>